/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author welcome
 */
public class breakfast extends javax.swing.JFrame {

    /**
     * Creates new form breakfast
     */
    int table_number;
    int dosa = 0,idly = 0,poori = 0, chapathi = 0,pongal = 0;
    int total=0;
    String driver = "org.apache.derby.jdbc.ClientDriver";
    Connection con = null;
    PreparedStatement pstmt = null;
    
    public breakfast() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        b9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        dosa_combo = new javax.swing.JComboBox<>();
        idly_combo = new javax.swing.JComboBox<>();
        pooriset_combo = new javax.swing.JComboBox<>();
        chapathi_combo = new javax.swing.JComboBox<>();
        pongal_combo = new javax.swing.JComboBox<>();
        table_number_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("BREAKFAST");

        l5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        l5.setText("DOSA      -  35 ₹");

        l6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        l6.setText("IDLY     -  8  ₹  ");

        l7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        l7.setText("POORISET  -  30 ₹    ");

        l8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        l8.setText("CHAPATHI     -  10 ₹");

        l9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        l9.setText("PONGAL  -  30 ₹ ");

        b9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/ordernow1.gif"))); // NOI18N
        b9.setAutoscrolls(true);
        b9.setBorderPainted(false);
        b9.setContentAreaFilled(false);
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.setFocusPainted(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Go To Menu ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        dosa_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dosa_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        dosa_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosa_comboActionPerformed(evt);
            }
        });

        idly_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        idly_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        idly_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idly_comboActionPerformed(evt);
            }
        });

        pooriset_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pooriset_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        pooriset_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pooriset_comboActionPerformed(evt);
            }
        });

        chapathi_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chapathi_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        chapathi_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapathi_comboActionPerformed(evt);
            }
        });

        pongal_combo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pongal_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        pongal_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pongal_comboActionPerformed(evt);
            }
        });

        table_number_combo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        table_number_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "table - 1", "table - 2", "table - 3", "table - 4", "table - 5", "table - 6", "table - 7" }));
        table_number_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table_number_comboActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/dosa.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/idly.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/poori.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/pongal.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/breakfast_images/chapathi.jpg"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("END ORDERS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dosa_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idly_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pooriset_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(l9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pongal_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(table_number_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(117, 117, 117))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(chapathi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(108, 108, 108)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(116, 116, 116)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(47, 47, 47)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(table_number_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pooriset_combo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idly_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dosa_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pongal_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l8)
                            .addComponent(chapathi_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        menu ml = new menu();
        ml.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
       
        
            table_number = table_number_combo.getSelectedIndex()+1;
            int res;
              
            String order="";
            //setVisible(false);
            if(dosa!=0)
            {
                order+=dosa+" - DOSA\n";
            }if(idly!=0)
            {
                order+=idly+" - IDLY\n";
            }
            if(poori!=0)
            {
                order+=poori+" - POORISET\n";
            }
            if(chapathi!=0)
            {
                order+=chapathi+" - CHAPATHI\n";
            }
            if(pongal!=0)
            {
                order+=pongal+" - PONGAL\n";
            }
            System.out.println(order);
            String confirm = "Are you surely going to order the following items\n"+order;
             if(JOptionPane.showConfirmDialog(this,confirm,"BREAKFAST",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
             {
                 res=(dosa*35)+(idly*8)+(poori*30)+(chapathi*10)+(pongal*30);
                 total+=res;
                String result1 = Integer.toString(total);
                //new receipt(result1).setVisible(false);
                new Breakfast_admin(result1).setVisible(true);
            
            try{
            Class.forName(driver);
            String url = "jdbc:derby://localhost:1527/restaurant";
            con =DriverManager.getConnection(url,"sundar","123");
            pstmt = con.prepareStatement("insert into breakfast_order (table_number,dosa,idly,poori,chapathi,pongal)values(?,?,?,?,?,?)");
            pstmt.setInt(1,table_number);
            pstmt.setInt(2,dosa);
            pstmt.setInt(3,idly);
            pstmt.setInt(4,poori);
            pstmt.setInt(5,chapathi);
            pstmt.setInt(6,pongal);
            
             pstmt.executeUpdate();
             //new Breakfast_admin().setVisible(true);
        
        }
        catch(Exception e)
        {
            System.out.println("SQL Exception "+e);
        }
    }
        
    }//GEN-LAST:event_b9ActionPerformed

    private void idly_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idly_comboActionPerformed
        // TODO add your handling code here:
        if(idly_combo.getSelectedIndex()==0) 
        {
           //t6.setText("");
            idly = 0;
        } 
        else if (idly_combo.getSelectedIndex()>0) 
        {
            //t6.setText(""+idly_combo.getSelectedItem());
            idly = Integer.parseInt(idly_combo.getSelectedItem().toString());
        }
        else
        {
           // t6.setText("");
        }
    }//GEN-LAST:event_idly_comboActionPerformed

    private void pooriset_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pooriset_comboActionPerformed
        // TODO add your handling code here:
        if(pooriset_combo.getSelectedIndex()==0) 
        {
           //t7.setText("");
            poori = 0;
        } 
        else {
           // t7.setText(""+pooriset_combo.getSelectedItem());
             poori = Integer.parseInt(pooriset_combo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_pooriset_comboActionPerformed

    private void chapathi_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapathi_comboActionPerformed
        // TODO add your handling code here:
        if(chapathi_combo.getSelectedIndex()==0) 
        {
           //t8.setText("");
            chapathi = 0;
        } 
        else {
            //t8.setText(""+chapathi_combo.getSelectedItem());
            chapathi = Integer.parseInt(chapathi_combo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_chapathi_comboActionPerformed

    private void pongal_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pongal_comboActionPerformed
        // TODO add your handling code here:
        if(pongal_combo.getSelectedIndex()==0) 
        {
           //t9.setText("");
            pongal = 0;
        } 
        else {
            //t9.setText(""+pongal_combo.getSelectedItem());
            pongal = Integer.parseInt(pongal_combo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_pongal_comboActionPerformed

    private void dosa_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosa_comboActionPerformed
        // TODO add your handling code here:
        if(dosa_combo.getSelectedIndex()==0) 
        {
           //t5.setText("");
        } 
        else {
           // t5.setText(""+dosa_combo.getSelectedItem());
            dosa = Integer.parseInt(dosa_combo.getSelectedItem().toString());
        }
    }//GEN-LAST:event_dosa_comboActionPerformed

    private void table_number_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table_number_comboActionPerformed
        table_number = table_number_combo.getSelectedIndex()+1;
    }//GEN-LAST:event_table_number_comboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Feedback().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(breakfast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new breakfast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b9;
    private javax.swing.JComboBox<String> chapathi_combo;
    private javax.swing.JComboBox<String> dosa_combo;
    private javax.swing.JComboBox<String> idly_combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JComboBox<String> pongal_combo;
    private javax.swing.JComboBox<String> pooriset_combo;
    private javax.swing.JComboBox<String> table_number_combo;
    // End of variables declaration//GEN-END:variables
}
