/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;
//import gamelauncher.Start.*;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Sundaresan.J
 */
public class Register extends javax.swing.JFrame
{

    /**
     * Creates new form Welcome
     */
         String driver = "org.apache.derby.jdbc.ClientDriver";
        Connection con = null;
        Statement stmt = null;
        PreparedStatement pstmt = null;
        String dburl = "jdbc:derby://localhost:1527/restaurant";
        String user_name = "sundar";
        String password = "123";
        
                                
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        userlabel = new javax.swing.JLabel();
        passwordlabel = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        mode = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        confirmlabel = new javax.swing.JLabel();
        con_pwd = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        email_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 51, 0));
        setName("Start"); // NOI18N
        setResizable(false);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(new javax.swing.border.MatteBorder(null));
        panel1.setForeground(new java.awt.Color(255, 0, 0));

        user.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        user.setForeground(new java.awt.Color(51, 51, 255));
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        user.setDisabledTextColor(new java.awt.Color(0, 51, 255));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        pwd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        userlabel.setForeground(java.awt.Color.magenta);
        userlabel.setText("UserName");

        passwordlabel.setBackground(new java.awt.Color(255, 204, 204));
        passwordlabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        passwordlabel.setForeground(java.awt.Color.magenta);
        passwordlabel.setText("Password");

        message1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        message1.setForeground(new java.awt.Color(255, 0, 51));

        register.setBackground(new java.awt.Color(0, 102, 204));
        register.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        register.setText("REGISTER");
        register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        mode.setText("Dark Mode");
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new loginlogo.png"))); // NOI18N

        confirmlabel.setBackground(new java.awt.Color(255, 204, 204));
        confirmlabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        confirmlabel.setForeground(java.awt.Color.magenta);
        confirmlabel.setText("Confirm Password");

        con_pwd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        con_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con_pwdActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setText("BACK");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        email_label.setBackground(new java.awt.Color(255, 204, 204));
        email_label.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        email_label.setForeground(java.awt.Color.magenta);
        email_label.setText("E-Mail Address");

        jLabel3.setText("(Optional)");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmlabel)
                    .addComponent(email_label))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(con_pwd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pwd, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                .addGap(0, 102, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mode))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(message1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(con_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(confirmlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(register))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        if(mode.getActionCommand().equals("Light Mode"))
        {
            mode.setText("Dark Mode");
            panel1.setBackground(Color.WHITE);
            userlabel.setForeground(Color.magenta);
            confirmlabel.setForeground(Color.magenta);
            email_label.setForeground(Color.magenta);
            passwordlabel.setForeground(Color.MAGENTA);
        }
        else
        {
            mode.setText("Light Mode");
            panel1.setBackground(Color.GRAY);
            userlabel.setForeground(Color.WHITE);
            confirmlabel.setForeground(Color.WHITE);
            email_label.setForeground(Color.WHITE);
            passwordlabel.setForeground(Color.WHITE);
            //login_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login dark.jpg")));
        }
    }//GEN-LAST:event_modeActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        int flag = 0;
        try
        {
            Class.forName(driver);
            con = DriverManager.getConnection(dburl,user_name,password);
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from restaurant_login");
            pstmt = con.prepareStatement("insert into restaurant_login values(?,?)");
            String u = user.getText();
            String p = pwd.getText();
            while(rs.next())
            {
                if(u.equals(rs.getString(1)))
                {
                        flag = 1;  
                }
            }
            if (flag == 1)
            {
                JOptionPane.showMessageDialog(this,"Username already exists..!", "Login", 1);
            }
            else
            {
                if(pwd.getText().length()>=8)
                {
                    if(pwd.getText().equals(con_pwd.getText()))
                    {
                        pstmt.setString(1,u);
                        pstmt.setString(2,p);
                        JOptionPane.showMessageDialog(this,"*Your account is registered successfully!\n"
                            + "Please remember this user name and password!");
                        new menu().setVisible(true);
                    }
                    else
                    {
                        message1.setText("Password mismatch...");
                        pwd.setBackground(Color.pink);
                        con_pwd.setBackground(Color.pink);
                    }
                }
                else
                {
                    message1.setText("Password should contain more than 8 characters");
                }
                pstmt.executeUpdate();
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }/*
        if(!user.getText().isEmpty()||pwd.getText().isEmpty())
        {
            if(pwd.getText().length()>=8)
            {
                if(pwd.getText().equals(con_pwd.getText()))
                {
                    new Start().setVisible(true);
                }
                else
                {
                    message1.setText("Password mismatch...");
                    pwd.setBackground(Color.pink);
                    con_pwd.setBackground(Color.pink);
                }    
            }
            else
            {
                message1.setText("Password should contain more than 8 characters");
            }
        }
        else
        {
            message1.setText("Please fill the required fields");
        }*/

        
    }//GEN-LAST:event_registerActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pwdActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void con_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_con_pwdActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField con_pwd;
    private javax.swing.JLabel confirmlabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_label;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel message1;
    private javax.swing.JButton mode;
    public javax.swing.JPanel panel1;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JButton register;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
